/*
 * RPM definition of OMAP GPIO controller @ljtale
 */

#include <linux/gpio.h>
#include <linux/io.h>
#include <linux/of.h>
#include <linux/pm_runtime.h>

#include <linux/universal-utils.h>

// register offsets
#define OMAP_GPIO_UNI_IRQENABLE1_REG        0x0034
#define OMAP_GPIO_UNI_IRQENABLE2_REG        0x0038
#define OMAP_GPIO_UNI_WAKE_EN_REG           0x0044 
#define OMAP_GPIO_UNI_CTRL_REG              0x0130
#define OMAP_GPIO_UNI_OE_REG                0x0134
#define OMAP_GPIO_UNI_LEVELDETECT0_REG      0x0140
#define OMAP_GPIO_UNI_LEVELDETECT1_REG      0x0144
#define OMAP_GPIO_UNI_RISINGDETECT_REG      0x0148
#define OMAP_GPIO_UNI_FALLINGDETECT_REG     0x014c
#define OMAP_GPIO_UNI_DATAOUT_REG           0x013c
#define OMAP_GPIO_UNI_DEBOUNCE_REG          0x0154
#define OMAP_GPIO_UNI_DEBOUNCE_EN_REG       0x0150

enum {
    OMAP_GPIO_UNI_ZERO = 0,
    OMAP_GPIO_UNI_IRQENABLE1,
    OMAP_GPIO_UNI_IRQENABLE2,
    OMAP_GPIO_UNI_WAKE_EN,
    OMAP_GPIO_UNI_CTRL,
    OMAP_GPIO_UNI_OE,
    OMAP_GPIO_UNI_LEVELDETECT0,
    OMAP_GPIO_UNI_LEVELDETECT1,
    OMAP_GPIO_UNI_RISINGDETECT,
    OMAP_GPIO_UNI_FALLINGDETECT,
    OMAP_GPIO_UNI_DATAOUT,
    OMAP_GPIO_UNI_DEBOUNCE,
    OMAP_GPIO_UNI_DEBOUNCE_EN,
};

static u32 omap_gpio_reg_context[] = {
    [OMAP_GPIO_UNI_ZERO] = 0,
    [OMAP_GPIO_UNI_IRQENABLE1] = 0,
    [OMAP_GPIO_UNI_IRQENABLE2] = 0,
    [OMAP_GPIO_UNI_WAKE_EN] = 0,
    [OMAP_GPIO_UNI_CTRL] = 0,
    [OMAP_GPIO_UNI_OE] = 0,
    [OMAP_GPIO_UNI_LEVELDETECT0] = 0,
    [OMAP_GPIO_UNI_LEVELDETECT1] = 0,
    [OMAP_GPIO_UNI_RISINGDETECT] = 0,
    [OMAP_GPIO_UNI_FALLINGDETECT] = 0,
    [OMAP_GPIO_UNI_DATAOUT] = 0,
    [OMAP_GPIO_UNI_DEBOUNCE] = 0,
    [OMAP_GPIO_UNI_DEBOUNCE_EN] = 0,
};

