# ljtale: Makefile for universal driver
# #
#

obj-y			+= central-pm.o
obj-y			+= universal-drv.o
obj-y			+= universal-core.o
obj-y			+= universal-rpm.o
obj-y			+= debug.o

lib-y			+= universal-core.o
lib-y			+= universal-drv.o
